### ISSUE TITLE
Poor conversion from dsl/stardict/xdxf to diсtd format 

### ISSUE THREAD

**Issue by Michahel** [soshial/xdxf_makedict#10]
After conversion from dsl to diсtd format appear HTML tags: 
&lt;k&gt;...&lt;/k&gt;, &lt;blockquote&gt;...&lt;/blockquote&gt;, &lt;kref&gt;...&lt;/kref&gt;
This formatting is not part of the DICT standard. I think for DICT format it is better, that was PlainText without these elements of formatting.
It is better the HTML tags &lt;kref&gt;...&lt;/kref&gt; to replace with format codes {...}, and all other tags to remove.
The above is true for other directions of conversion. For example, from stardict to dictd and from xdxf to dictd.

**Comment by soshial** [comment]
I am closing the issue, because the converter has been deprecated. Please use other converters like [pyglossary](https://github.com/ilius/pyglossary).
