### ISSUE TITLE
self test fails

### ISSUE THREAD

**Issue by ildar** [soshial/xdxf_makedict#11]
make test:
69% tests passed, 4 tests failed out of 13

Total Test time (real) =  18.53 sec

The following tests FAILED:
      2 - t_dslparser (Failed)
      5 - t_xdxfgenerator (Failed)
     10 - t_parser_options (Failed)
     11 - t_sdict_parser (Failed)

Is it not?

**Comment by soshial** [comment]
I am closing the issue, because the converter has been deprecated. Please use other converters like [pyglossary](https://github.com/ilius/pyglossary).
