### ISSUE TITLE
Magic string did not match when converting from stardict

### ISSUE THREAD

**Issue by twardoch** [soshial/xdxf_makedict#14]
If the IFO StarDict file is saved as "UTF-8 with BOM" (which is commonly the case), then I get the error "Magic string did not match". I suggest to make the comparison for the magic string more robust and tolerate the BOM (i.e. 0xEF,0xBB,0xBF at the beginning of the file before the "actual" magic string).

**Comment by soshial** [comment]
I am closing the issue, because the converter has been deprecated. Please use other converters like [pyglossary](https://github.com/ilius/pyglossary).
