### ISSUE TITLE
#include <cstdlib> missing in file.hpp

### ISSUE THREAD

**Issue by twardoch** [soshial/xdxf_makedict#15]
When trying to build makedict on Mac OS X 10.9, I was getting errors: 
/dictd_parser.cpp:164:10: Use of undeclared identifier 'EXIT_FAILURE'

I fixed this by adding
# include <cstdlib>

to file.hpp

Now it compiles fine.

**Comment by soshial** [comment]
I am closing the issue, because the converter has been deprecated. Please use other converters like [pyglossary](https://github.com/ilius/pyglossary).
