### ISSUE TITLE
Link error - ld cannot find glib-2.0

### ISSUE THREAD

**Issue by nomorethirst** [soshial/xdxf_makedict#19]
$ cd Dropbox/Documents/xdxf_makedict_build
$ cmake ../xdxf_makedict
-- The C compiler identification is AppleClang 5.1.0.5030040
-- The CXX compiler identification is AppleClang 5.1.0.5030040
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PkgConfig: /opt/local/bin/pkg-config (found version "0.28") 
-- checking for one of the modules 'glib-2.0'
-- Found GLib2: glib-2.0;intl /opt/local/include/glib-2.0;/opt/local/lib/glib-2.0/include;/opt/local/include
-- Looking for include file glib/gregex.h
-- Looking for include file glib/gregex.h - not found
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.5") 
-- Found Gettext: /opt/local/bin/msgmerge (found version "0.18.3") 
-- Performing Test ICONV_HAVE_WERROR
-- Performing Test ICONV_HAVE_WERROR - Success
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST - Failed
-- Found Iconv: /usr/lib/libiconv.dylib
-- Looking for dgettext
-- Looking for dgettext - not found
-- Found libintl: /opt/local/lib/libintl.dylib
-- Looking for mmap
-- Looking for mmap - found
-- Looking for locale.h
-- Looking for locale.h - found
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/nomorethirst/Dropbox/Documents/xdxf_makedict_build
$ make
Scanning dependencies of target makedict
[  3%] Building CXX object CMakeFiles/makedict.dir/src/makedict.cpp.o
[  7%] Building CXX object CMakeFiles/makedict.dir/src/file.cpp.o
[ 11%] Building CXX object CMakeFiles/makedict.dir/src/parser.cpp.o
[ 15%] Building CXX object CMakeFiles/makedict.dir/src/generator.cpp.o
[ 19%] Building CXX object CMakeFiles/makedict.dir/src/process.cpp.o
[ 23%] Building CXX object CMakeFiles/makedict.dir/src/connector.cpp.o
[ 26%] Building CXX object CMakeFiles/makedict.dir/src/log.cpp.o
[ 30%] Building CXX object CMakeFiles/makedict.dir/src/utils.cpp.o
[ 34%] Building CXX object CMakeFiles/makedict.dir/src/xml.cpp.o
[ 38%] Building CXX object CMakeFiles/makedict.dir/src/charset_conv.cpp.o
[ 42%] Building CXX object CMakeFiles/makedict.dir/src/dictd_generator.cpp.o
[ 46%] Building CXX object CMakeFiles/makedict.dir/src/dictd_parser.cpp.o
[ 50%] Building CXX object CMakeFiles/makedict.dir/src/dsl_ipa.cpp.o
[ 53%] Building CXX object CMakeFiles/makedict.dir/src/dsl_parser.cpp.o
[ 57%] Building CXX object CMakeFiles/makedict.dir/src/dummy_generator.cpp.o
[ 61%] Building CXX object CMakeFiles/makedict.dir/src/dummy_parser.cpp.o
[ 65%] Building CXX object CMakeFiles/makedict.dir/src/lang_tbl.cpp.o
[ 69%] Building CXX object CMakeFiles/makedict.dir/src/lang_tbl_auto.cpp.o
[ 73%] Building CXX object CMakeFiles/makedict.dir/src/mapfile.cpp.o
[ 76%] Building CXX object CMakeFiles/makedict.dir/src/normalize_tags.cpp.o
[ 80%] Building CXX object CMakeFiles/makedict.dir/src/sdict_parser.cpp.o
[ 84%] Building CXX object CMakeFiles/makedict.dir/src/stardict_generator.cpp.o
[ 88%] Building CXX object CMakeFiles/makedict.dir/src/stardict_parser.cpp.o
[ 92%] Building CXX object CMakeFiles/makedict.dir/src/xdxf_generator.cpp.o
[ 96%] Building CXX object CMakeFiles/makedict.dir/src/xdxf_parser.cpp.o
Linking CXX executable makedict
ld: library not found for -lglib-2.0
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [makedict] Error 1
make[1]: **\* [CMakeFiles/makedict.dir/all] Error 2
make: **\* [all] Error 2

**Comment by soshial** [comment]
I am closing the issue, because the converter has been deprecated. Please use other converters like [pyglossary](https://github.com/ilius/pyglossary).
