### ISSUE TITLE
Compile error with glib-2.40.0: variable or field ‘g_log’ declared void

### ISSUE THREAD

**Issue by erosennin** [soshial/xdxf_makedict#20]
glib has its own g_log() macro since version 2.40.0 which conflicts with g_log() in log.hpp:

    [  3%] Building CXX object CMakeFiles/makedict.dir/src/makedict.cpp.o
    In file included from /tmp/xdxf_makedict/src/parser.hpp:37:0,
                     from /tmp/xdxf_makedict/src/connector.hpp:4,
                     from /tmp/xdxf_makedict/src/makedict.cpp:37:
    /tmp/xdxf_makedict/src/log.hpp:22:13: error: variable or field ‘g_log’ declared void
    /tmp/xdxf_makedict/src/log.hpp:22:13: error: expected primary-expression before ‘const’
    /tmp/xdxf_makedict/src/log.hpp:22:13: error: expected primary-expression before ‘...’ token
    make[2]: *** [CMakeFiles/makedict.dir/src/makedict.cpp.o] Error 1
    make[1]: *** [CMakeFiles/makedict.dir/all] Error 2
    make: *** [all] Error 2

Removing g_log() from log.hpp and log.cpp fixed the erorr for me.

**Comment by leoboiko** [comment]
Same problem here, lidar's patch works.

**Comment by soshial** [comment]
I merged the branches. Problem fixed.
