### ISSUE TITLE
Some contradictions

### ISSUE THREAD

**Issue by anohren** [soshial/xdxf_makedict#28]
I skimmed through the standard and found that this sentence:

> "The choice of how they have to be rendered is shifted to dictionary-browsing software ("DS"), its settings and user preferences"

have some conflicts in the text which are found by searching for e.g. "DS should" and "DS must".

cheers

**Comment by soshial** [comment]
All the requirements that are listed in the standard are not about appearance of a word article. **How** it has look like is delegated to DS. If I am mistaken somewhere in the standard please tell me.

**Comment by anohren** [comment]
To me it seems like directives like these are explicitly prescribing appearances of articles: 

> "For articles that have logical format DS must distinguish visually one definition from another according to nesting level by means of indentation, font size or enumeration definitions with '1)','2)'... or 1.','2.'... or 'A.','B.'... etc"

**Comment by soshial** [comment]
I would say that all listed directives explain how XDXF articles should be logically structured and how intended features of the format should be implemented to be more useful for users. Visual representation of this structure and features, e.g. how it is supposed to look — is assigned to dictionary browser.

For example, enumeration of sub definitions should be reflected by dictionary browser, but how it will be done (colour, indentation or maybe even listing/scrolling them horizontally) is solely the DS prerogative.

**Comment by anohren** [comment]
I seem to recall finding more than one example. The instructions on how to find them is in the first post. 

> Visual representation of this structure and features, e.g. how it is supposed to look — is assigned to dictionary browser.

As my example illustrated, that isn't how the paragraph is worded. 

> DS must distinguish visually

I guess an audio only DS is out of the question then...

**Comment by soshial** [comment]
Thanks. I reworded the mentioned places.
