### ISSUE TITLE
kref link displaying one piece of text and linking to another?

### ISSUE THREAD

**Issue by darnn** [soshial/xdxf_makedict#34]
Hi. I'm trying to convert a dictionary I have to XDXF. Using makedict, I get a file with things like this in it:
`<A href="bword://aaa">bbb</A>`
That's meant to link to "aaa" while displaying the text "bbb". Is there any way to achieve this with kref?

**Comment by nikita-moor** [comment]
Yes, first you define an anchor with `id` and then reference it with `<kref>` tag:

```xml
<ar>
  <k id="aaa">first</k>
  <def><deftext>Something about the word "first".</deftext></def>
</ar>
<ar>
  <k>second</k>
  <def><deftext>Here is a <kref idref="aaa">link</kref> to previous article.</deftext></def>
</ar>
```
However, it was not yet [implemented in GoldenDict][1], i.e. you can write it in XDXF, but it will not work in real computer shells.

[1]: https://github.com/goldendict/goldendict/blob/5b696eac5b3d85a2a57bb8437d86ab0c41b28689/xdxf2html.cc#L323

**Comment by darnn** [comment]
I see! Thank you!
Would I have any way of knowing when they do implement it, or should I just be trying every new Windows build until I see it works?

**Comment by nikita-moor** [comment]
I'm not a developer of GoldenDict. As far as I know, developing of all dictionary shells for desktop computers stoped 5 or 6 years ago. GoldenDict developers do commit patches, but it's only small bugfixes. (Howevere, they were very kind to adapt new hunspell output for me.)

If you create a dictionary especially for GoldenDict, then this kind of link does work:

``` html
Here is a <a href="first">link</a> to the previous article.
```

**Comment by darnn** [comment]
Oh, great! Thank you!
And yeah, I realized you weren't a GoldenDict developer, I just figured maybe you'd know what to look for in their changelog or something. It's too bad they're not actively developing it, I always recommend it to my translator friends whenever they complain about how poor Babylon's support is, but it doesn't seem to work properly on certain versions of Windows 10, for instance.
Anyway, this solves everything for me, so I'm closing it. Thanks again.

**Comment by k-sl** [comment]
> If `<kref>` has `idref` attribute, then it references the `<def>` tag that has an `id` equal to this attribute. The word "answered" in code `<kref idref"nf0837glo9">answered</kref>` will link to the verb "answer" (and not the noun because of the specific `id`).

This has been part of the specification for quite some time, I'd expect it to be supported in GoldenDict, although I haven't tried it myself. If it isn't you can create an issue on their project. GoldenDict isn't dead, just not very active. In any case, that's an issue for their project.

**Comment by nikita-moor** [comment]
Our master @soshial already opened the issue ["links not to the whole article"](https://github.com/goldendict/goldendict/issues/348) (2013 year).

GodlenDict does not recognize attributes in quotations too, `author` and `source`:

```xml
<ex author="Plutarch" source="Life of Caesar">
  <ex_orig >Veni, vidi, vici</ex_orig>
  <ex_tran>I came; I saw; I conquered</ex_tran>
</ex>
```

would be

> Veni, vidi, vici ~ I came; I saw; I conquered

Several things are needed to be improved in GoldenDict's support of XDXF format.
