### ISSUE TITLE
zho for chinese

### ISSUE THREAD

**Issue by mbingenheimer** [soshial/xdxf_makedict#40]
Regarding the use of ISO language standards on <xdfx> in  @lang_from @lang_to:
1) I believe these should be lower case according to ISO 639-3
2) It might make sense to add all languages, the space needed is negligible. If making a selection perhaps focus on the largest ones: e.g. Chinese "zho" is not in the DTD, but the much rarer  "zha" Chuang/Zhuang is.

**Comment by soshial** [comment]
I have updated the format specification to rev. 34. The new revision should support all of [BCP47](https://en.wikipedia.org/wiki/IETF_language_tag) languages, variants and scripts.

**Comment by mbingenheimer** [comment]
Super. Thanks so much.
