### ISSUE TITLE
How can I add image to XDXF file?

### ISSUE THREAD

**Issue by dongta11721** [soshial/xdxf_makedict#42]
Hello!
Please help me to add image into xdxf! The image is in the same directory of xdxf file. 

Thank!

**Comment by nikita-moor** [comment]
Image: `<rref lctn="picture.png" type="image/png" />`. Doesn't it work?

**Comment by dongta11721** [comment]
Thank for response, nikita-moor. I tried your tags but It did not work.  It shows nothing. I don't know what happen. Please help me !
Thank you

**Comment by nikita-moor** [comment]
You better be more specific. XDXF is just a file format. When you say "It did not work" you mean that a dictionary shell (GoldenDict, Alpus?) does not parse it correctly (i.e. does not show the image). Then, it is not a problem of the format but of implementation. You could try preparing an example and submitting an issue to the appropriate application (GoldenDict is [here](https://github.com/goldendict/goldendict/issues)).

For example: [xdxf-image.zip](https://github.com/soshial/xdxf_makedict/files/7967857/xdxf-image.zip).

Opening the example in **GoldenDict**, you can see that it does not support new version of XDXF, so you need to code your images old-way as `<img src="cat.png" />`:

![Screenshot_2022-01-31_08-28-02](https://user-images.githubusercontent.com/13879891/151734949-4dd9cf8d-864d-42e0-baee-d39efb869002.png)

If your goal is **Alpus** then you will need to compress all images into a zip file (I don't remember filename convention).

**Comment by soshial** [comment]
Thanks, @nikita-moor, I think this is the right explanation, why it doesn't work as of now.
