### ISSUE TITLE
Problem with DTD

### ISSUE THREAD

**Issue by boydkelly** [soshial/xdxf_makedict#45]
Running xmllint with the dtd and sample data produces this error.  It seems to not even want the |br at all in the dtd.

````
xmllint --dtdvalid xdxf_strict.dtd rev34.xml 
xdxf_strict.dtd:13: parser error : MixedContentDecl : '|' or ')*' expected
<!ELEMENT description (#PCDATA|br)>
                                 ^
xdxf_strict.dtd:13: parser error : expected '>'
<!ELEMENT description (#PCDATA|br)>
                                 ^
xdxf_strict.dtd:13: parser error : Content error in the external subset
<!ELEMENT description (#PCDATA|br)>
````

**Comment by boydkelly** [comment]
This is what I did.  https://gitlab.com/ci-dict/dyu-xdxf/-/blob/main/xdxf_strict.dtd

Very little activity here....

**Comment by boydkelly** [comment]
Its such a shame that these guys don't collaborate somewhat more...   And communicate.

**Comment by soshial** [comment]
I am sorry for such long delays, @boydkelly. The Russian aggression against Ukraine impacted my participation in the project.

**Comment by soshial** [comment]
BTW, @boydkelly, I looked at your changed standard (https://gitlab.com/ci-dict/dyu-xdxf/-/blob/main/xdxf_strict.dtd).

1. I am curious, what is your project about? Is it about West-African languages?
2. Why did you decide to add `def-id` and `ex-id` attributes? 
3. Why did you decide to change `<!ELEMENT categ (kref+)>` to `<!ELEMENT categ (#PCDATA|kref)*>`?
