### ISSUE TITLE
undefined reference to File::__printf__

### ISSUE THREAD

**Issue by jarekczek** [soshial/xdxf_makedict#7]
I had problems compiling under msys. Finally I succeeded and that's the comment from the fix:

/\* Msys/mingw printf problem:
   libintl defines macro printf which messes with our File::printf function.
   It seems to me, that it happens after including glib/gil8n.h
   On the other hand it is reset by cstdio header, so I changed the order
   of includes, so that cstdio come after gil8n.h

I'm going to attach the patch, if it's possible.

UPD: I put the patch into my repository, that's [the link](https://github.com/jarekczek/various_files/blob/master/makedict/printf.patch).

**Comment by soshial** [comment]
I am closing the issue, because the converter has been deprecated. Please use other converters like [pyglossary](https://github.com/ilius/pyglossary).
